---
- name: Uninstall MongoDB Router Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    purge: yes
    state: absent
  with_items:
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools
  when:
    - mongo_distribution == 'mongodb-org'
    - inventory_hostname in groups['mongos']

- name: Uninstall MongoDB Node Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    purge: yes
    state: absent
  with_items:
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-tools
  when:
    - mongo_distribution == 'mongodb-org'
    - inventory_hostname not in groups['mongos']

- name: Uninstall MongoDB Repository
  file:
    path: /etc/apt/sources.list.d/mongodb-org-{{ mongo_version_major }}.{{ mongo_version_minor }}.list
    state: absent
  when:
    - mongo_distribution == 'mongodb-org'

# - name: Uninstall MongoDB Keyring
#   apt_key:
#     url: "https://www.mongodb.org/static/pgp/server-{{ mongo_version_major }}.{{ mongo_version_minor }}.asc"
#     state: absent
#   when:
#     - mongo_distribution == 'mongodb-org'
