---
- name: Wait for 5 Seconds Before Unmounting ZFS Dataset
  wait_for:
    timeout: 5

- name: Unmount ZFS Dataset to MongoDB Data Directory
  mount:
    path: /var/lib/mongodb/data
    state: absent

- name: Unmount ZFS Dataset to MongoDB Log Directory
  mount:
    path: /var/lib/mongodb/log
    state: absent

- name: Unmount ZFS Dataset to MongoDB PKI Directory
  mount:
    path: /var/lib/mongodb/pki
    state: absent

- name: Wait for 5 Seconds After Unmounting ZFS Dataset
  wait_for:
    timeout: 5
