---
- name: Wait for 5 Seconds Before Unmounting ZFS Dataset
  wait_for:
    timeout: 5

- name: Unmount ZFS Dataset from MongoDB Directory
  shell: "zfs umount {{ zfs_pool_name }}/mongodb"

- name: Wait for 5 Seconds After Unmounting ZFS Dataset
  wait_for:
    timeout: 5
