---
- include: facts.yml

- include: apparmor_services.yml

- include: os_packages.yml

- include: zfs_packages.yml
  when:
    - inventory_hostname in groups['mongoc'] or inventory_hostname in groups['mongod']
    - zfs_backend

- include: zfs_blocks.yml
  when:
    - inventory_hostname in groups['mongoc'] or inventory_hostname in groups['mongod']
    - zfs_backend

- include: mongo_users.yml

- include: mongo_packages.yml

- include: mongo_services.yml

- include: mongo_cleanups.yml

- include: zfs_mounts.yml
  when:
    - inventory_hostname in groups['mongoc'] or inventory_hostname in groups['mongod']
    - zfs_backend

- include: mongo_directories.yml

- include: mongo_keys.yml

- include: python_packages.yml

- include: os_cleanups.yml
