---
- name: Create MongoDB Databases Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: mongodb
    group: mongodb
    recurse: true
  with_items:
    - /var/lib/mongodb
    - /var/lib/mongodb/data
    - /var/lib/mongodb/log
    - /var/lib/mongodb/pki

- name: Create MongoDB Run Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: mongodb
    group: mongodb
    recurse: true
  with_items:
    - /var/run/mongodb

- name: Create MongoDB Logs Directory
  file:
    src: /var/lib/mongodb/log
    dest: /var/log/mongodb
    owner: mongodb
    group: mongodb
    state: link
