---
- name: Install Python PIP Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    state: present
  with_items:
    - python-pip

- name: Install PyMongo Packages from Python PIP
  pip:
    name: pymongo
    extra_args: "--index-url https://pypi.python.org/simple"
    use_mirrors: no
    state: latest
