---
- name: Wait for 5 Seconds Before Mounting ZFS Dataset
  wait_for:
    timeout: 5

- name: Mount ZFS Dataset to MongoDB Directory
  shell: "zfs mount {{ zfs_pool_name }}/mongodb || true"

- name: Wait for 5 Seconds After Mounting ZFS Dataset
  wait_for:
    timeout: 5
