---
- name: Install ZFS PPA Repository
  apt_repository:
    repo: "ppa:jonathonf/zfs"

- name: Install ZFS Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    dpkg_options: "force-confdef,force-confold,force-confmiss"
    state: present
  with_items:
    - zfs-dkms
    - zfsutils-linux
