---
- name: Create Disabled Cron Directory
  file:
    path: /etc/cron.disabled
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: true
  when:
    - zfs_disable_cron

- name: Add Divert ZFS Utility Cron Job
  shell: "dpkg-divert --add --rename --divert /etc/cron.disabled/zfsutils-linux /etc/cron.d/zfsutils-linux"
  when:
    - zfs_disable_cron
